// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA7VlD_xAsle-gmzISTstgwquSW6qsuyo',
    appId: '1:231358910287:web:a17ab3c6efd4f5cb09bf3a',
    messagingSenderId: '231358910287',
    projectId: 'bookcoock-ab8be',
    authDomain: 'bookcoock-ab8be.firebaseapp.com',
    storageBucket: 'bookcoock-ab8be.firebasestorage.app',
    measurementId: 'G-M93KKYMP2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2b5Ht3MiXLYxSTlyI2Mz_hKcohQqTug',
    appId: '1:231358910287:android:73db85e8e2b3291109bf3a',
    messagingSenderId: '231358910287',
    projectId: 'bookcoock-ab8be',
    storageBucket: 'bookcoock-ab8be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABbILZbsEsnS6i3DHlD1eNK4zjURk0yyw',
    appId: '1:231358910287:ios:061ef4c5de70cb6f09bf3a',
    messagingSenderId: '231358910287',
    projectId: 'bookcoock-ab8be',
    storageBucket: 'bookcoock-ab8be.firebasestorage.app',
    iosBundleId: 'com.example.recipbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABbILZbsEsnS6i3DHlD1eNK4zjURk0yyw',
    appId: '1:231358910287:ios:061ef4c5de70cb6f09bf3a',
    messagingSenderId: '231358910287',
    projectId: 'bookcoock-ab8be',
    storageBucket: 'bookcoock-ab8be.firebasestorage.app',
    iosBundleId: 'com.example.recipbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA7VlD_xAsle-gmzISTstgwquSW6qsuyo',
    appId: '1:231358910287:web:024fabb38a55a32909bf3a',
    messagingSenderId: '231358910287',
    projectId: 'bookcoock-ab8be',
    authDomain: 'bookcoock-ab8be.firebaseapp.com',
    storageBucket: 'bookcoock-ab8be.firebasestorage.app',
    measurementId: 'G-B810FP39DD',
  );
}
